### PR TITLE
Remove version constraint

### PR DESCRIPTION
**Pull request by danrabinowitz**

### CODE REVIEW

**Comment by jverdeyen** [comment]
@veloxy should we release different versions/tags?

**Comment by veloxy** [comment]
@jverdeyen You mean for 0.5.x and 0.6.x? I don't really see a reason as we're only using the SMTP settings and nothing seems to be changed there. The release notes don't mention any breaking changes anyway.

**Comment by MiguelSavignano** [comment]
Hi @veloxy 

In my case I have a breaking change, mailcatcher 0.5.12 not show html previews for content type multipart/alternative but in 0.6.5 the html previews is correctly.

**Comment by veloxy** [comment]
@MiguelSavignano Yep, we noticed that too. We're using mailhog now instead, looks better than mailcatcher and does the same. But I'll merge this one so it will be fixed at least, I kind of lost track of this issue. 😬

**Comment by veloxy** [comment]
It's currently building, let me know if everything is okay! https://hub.docker.com/r/yappabe/mailcatcher/builds/

**Pull request merged**
